### ISSUE TITLE
Add tutorial videos to docs page & TOC

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-metal#475]
### What is the documentation modification?
 Add video page and link in TOC like this 
![image](https://user-images.githubusercontent.com/15937254/114902687-10822100-9de4-11eb-9976-d47d6dd1a4e7.png)

to the video playlist 

https://www.youtube.com/watch?v=bsrsKZLTkTo&list=PLOFEBzvs-VvqHl5ZqVmhB_FcSqmLufsjb&index=2&ab_channel=Qiskit 

Can embed playlist or maybe better yet, link to playlist but also listinvidiaully each video with embed, see 

* https://techwritingmatters.com/documenting-with-sphinx-tutorial-part-3-writing
* https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/YoutubeVideos.html

Also add a link to the README.

**Comment by marcolincs** [comment]
good idea.

**Comment by JeremyDrysdale-ibm** [comment]
It seems to me that a link to the playlist is sufficient over embedding individual videos at this time since the playlist is updating as new videos are being made and published.

I suggest
- Link to the YouTube playlist now
- Add a page to the docs with embedded videos when we have completed the current round of video tutorial sessions

Otherwise, we are stuck updating the docs to embed new videos as each one is published.
