### ISSUE TITLE
Enable higher python versions, all OSes, and pip venv

### ISSUE THREAD

**Issue by marcolincs** [Qiskit/qiskit-metal#514]
Observations on Windows:

Removing python limitation installs python 3.9 but leads to a shiboken2 error when importing pyside2.
Observations: the pip install of qiskit-metal overwrites the conda pyside2 install
- conda has pyside2 5.13 (max version for all python versions)
- PyPL has only pyside2 5.15.2 for python 3.9 (5.14 for 3.8 and 5.13 for 3.7)

Tests:
- Removing pyside2 from requirements.txt keeps the 5.13 conda version, which works well, thus the qiskit-metal installation leads to successful execution
- Doing the opposite (removing pyside2 dependency from environment.yml) leads to a jupyter notebook kernel crash during creation of a design
- however we need pyside2 in both requirements.txt and environment.yml to be able to deploy qiskit-metal to PyPI, so we need to find a way to make things work for both conda and PyPI deploys on a variety of python versions.

Todo:
- More tests to find optimal installation flows for all three cases: conda, PyPI and github clone, for a variety of python versions.

**Comment by JeremyDrysdale-ibm** [comment]
One thing to also consider about version 3.9.  We can see deprecation warnings about some stuff that will go away in version 3.9.  These are easy to find -- just run the tests.

One example, but there may be others besides collections.abc
![image](https://user-images.githubusercontent.com/68995878/117466670-fb02a180-af20-11eb-9b6f-3451fd6649b0.png)

**Comment by marcolincs** [comment]
conda python 3.9

Root cause: pyside2 5.15.1 and 5.15.2 from PyPI are incompatible with conda, causing `NameError: name '_init_pyside_extension' is not defined`. This is likely not to have resolution, just workarounds as described below:

In requirements.txt, either:
- if you accept to use `python<3.9`, make `pyside2<5.15.1`
- if you want to use `python>=3.9` remove `pyside2` from the requirements.txt (this will use the pyside2 that conda installs (5.13.2)

----finally:
requirements.txt has contrasting requirements. On one hand (PyPI packaging) we can let python and pyside2 versions free. On the other hand (conda packaging) we want to not have the pyside2 in the requirements.txt, but only in the environment.yml

**Comment by marcolincs** [comment]
Repeated the conda python 3.9 test on linux:
Result: same as windows (has to remove pyside2 from the requirements.txt to avoid the violation, or make it <5.15.1 and accept python 3.8)

Repeated the pip install tests on linux:
Result: for both `python venv` and `conda env`, fiona is not a problem here, but kernel dies on import of qiskit-metal. Further analysis is needed to determine a workaround

new info for FAQ:
During qiskit-metal installation (either during venv generation or around gdspy) you might get a gcc or python related error. To fix this error run something like this (specify the python version as needed): `sudo apt-get install gcc g++ python3-dev python3-venv`

**Comment by wshanks** [comment]
Here are some things I noticed while looking into this:

1. I tried removing the version constraint on PySide2 in environment.yml and the version constraint on Python in environment.yml and in setup.py. Then `conda env create -f environment.yml` installs Python 3.9 and PySide2 5.13.2. `pip install -e .` still leads to pip reinstalling PySide2 5.13.2 (I left the <5.14 constraint in requirements.txt) even though the wheel name does not list 39 (`PySide2-5.13.2-5.13.2-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl`). I did not check if this version of PySide2 actually works in Python 3.9. I think the reason PySide2 gets reinstalled is because of [a packaging metadata problem](https://github.com/conda-forge/pyside2-feedstock/issues/84) -- pip does not recognize the conda PySide2 install. There are a couple ways to deal with this:
    * As a temporary hack, some logic could be added to setup.py that checks if a compatible `PySide2` is already installed and removes it from `install_requires` if so. When a conda package with better metadata is published, this could be removed.
    * The recommended install procedure for using conda could be changed from `pip install -e .` to `pip install --no-deps -e .`.  This will just install metal without any dependencies. As long as environment.yml is maintained so that it includes all the needed dependencies this is fine.

2. I noticed that `pip install -e .` was also modifying other conda packages. `jedi` and `ipython` were being modified because the version constraints in requirements.txt do not match those in environment.yml. These should be kept in sync. docutils, MarkupSafe, and Jinja2 were also modified because the conda sphinx package does not specify the proper version constraints. I opened https://github.com/conda-forge/sphinx-feedstock/pull/99 about that.

**Comment by marcolincs** [comment]
Decisions after 5/13/2021 meeting:

- [ ] Add the `--no-deps` to the github-based installation instructions (prevents package overwrite)
- [ ] Explore the possibility to release also a conda package (not just PyPI)
- [ ] Modify setup.py to sense the window OS and give the appropriate instructions for gdal, fiona and shapely (as above).
- [ ] Update README to be suitable for the PyPI front page (instructions should be directed to PyPI users. while the github instructions should be referred to from a sub-section or from a separate image.

**Comment by marcolincs** [comment]
All the changes related to this issue are in the branch: `dependencies-cleanup-ext`
